name: Simple Job

on:
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest  # You can change the runner to another OS if needed

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Run Simple Job
        run: echo "Hello, GitHub Actions!"

