name: Manual Workflow Trigger

on:
  workflow_dispatch:

jobs:
  simple_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Print Message
        run: echo "This workflow was manually triggered."
