name: Simple Job

on:
  push:
    branches:
      - main  # Change 'main' to the branch you want to trigger the workflow on

jobs:
  build:
    runs-on: ubuntu-latest  # You can change the runner to another OS if needed

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Run Simple Job
        run: echo "Hello, GitHub Actions!"

